### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Shadyman** [sparkfun/Transceiver_Breakout-nRF24LU1_RP-SMA#1]
Hi!

The License.md text says "Creative Commons ShareAlike 4.0 International" (CC-SA 4.0 Intl) but the link on that text and the text that follows it suggests that it's "Creative Commons Attribution-ShareAlike 4.0 International" (CC-BY-SA 4.0 Intl).

Thanks!

**Comment by santaimpersonator** [comment]
I believe those nomenclatures are both one and the same, where the attribution can be inferred (although, I'm not an expert on the subject).

**Officially:** Attribution is required as stated in the [`README.md`](https://github.com/sparkfun/Transceiver_Breakout-nRF24LU1_RP-SMA/blob/master/README.md#license-information) and [`LICENSE.md`](https://github.com/sparkfun/Transceiver_Breakout-nRF24LU1_RP-SMA/blob/master/LICENSE.md) files.

I am closing this issue, for further questions on licensing please reach out to our [support team](https://www.sparkfun.com/support).
